### ISSUE TITLE
AS a user, I want to be able to list all the effects I have in my inventory

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#101]
SO THAT I can see what effects I have I can use

## Acceptance Criteria

GIVEN I am a user
WHEN I run `/effects list`
THEN I will see a list of effects that I can use
AND what effect, if any, I have applied currently

## Subtasks

- [ ] Create base `/effects` command
- [ ] Create `/effects list` subcommand
- [ ] Create paginated button event
- [ ] Update tests

## Notes

*No notes*

**Comment by Vylpes** [comment]
Need effect concept in first

**Comment by Vylpes** [comment]
[321-379 List all effects.pdf](https://github.com/user-attachments/files/17784498/321-379.List.all.effects.pdf)
