### ISSUE TITLE
AS a user, I want to be able to buy more effects

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#103]
SO THAT I can apply more effects to my user

## Acceptance Criteria

GIVEN I am a user
WHEN I run `/effects buy <id>`
THEN I will be able to buy the id effect

## Subtasks

- [ ] Create `/effects buy` subcommand
- [ ] Create `effects buy confirmation` button event
- [ ] Create `effects buy cancel` button event
- [ ] Update tests

## Notes

*No notes*

**Comment by Vylpes** [comment]
Need effect concept
