### ISSUE TITLE
AS a user, I want the multidrop command to give me a summary of the drop after it has completed

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#104]
SO THAT I can see what I've claimed and sacrificed

## Acceptance Criteria

GIVEN I'm a user
WHEN I finish the multidrop queue
THEN the finished embed will give me a summary on what I sacrificed, kept, and my new balance

## Subtasks

- [ ] Update database to store multidrop information
- [ ] Add embed summary
- [ ] Add background function to clear out expired multidrops from the database
- [ ] Update tests

## Notes

- The details it should give are: What was sacrificed, what was kept, and the user's new balance
