### ISSUE TITLE
Create /booster use subcommand

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#109]
*No description*

## Acceptance Criteria

GIVEN I am a user with a booster pack
WHEN I run the `/booster use <id>` command
THEN I will open the booster pack of `id` from my inventory

## Subtasks

- [ ] Create `/booster use` subcommand
- [ ] Create confirmation button event
- [ ] Create cancel button event

## Notes

*No notes*

**Comment by Vylpes** [comment]
Need base booster command
