### ISSUE TITLE
AS a developer and tester, I want a stage-only command to let me drop a random card of a chosen rarity

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#11]
AS a developer and tester, I want a stage-only command to let me drop a random card of a chosen rarity
SO THAT I can test that rarity's cards without developer intervention

## Acceptance Criteria
AS a developer and tester
GIVEN I want to test all cards of a specific rarity
WHEN I type `/droprarity <rarity>`
THEN the bot will pick a random card of that rarity

AS a developer and tester
GIVEN I want to test all cards
WHEN I type `/drop`
THEN the bot should ignore all existing environment variables for it

## Subtasks
- [ ] Create `/droprarity` command
- [ ] Create `/droprarity` reroll event
- [ ] Remove rarity environment variable

## Notes
- We should also remove the environment variable as it won't be needed anymore
