### ISSUE TITLE
Create /booster buy subcommand

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#110]
*No description*

## Acceptance Criteria

GIVEN I am a user without a booster pack
WHEN I run the `/booster buy <id>` command
THEN I will be able to buy a booster pack for the series `id`

## Subtasks

- [ ] Create `/booster buy` subcommand
- [ ] Create buy booster confirmation button event
- [ ] Create buy booster cancel button event

## Notes

*No notes*

**Comment by Vylpes** [comment]
Need base booster command
