### ISSUE TITLE
AS a developer, I want there to be documentation about the code and how to set the project up

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#13]
AS a developer, I want there to be documentation about the code and how to set the project up
SO THAT anyone can learn how the bot works and how to set it up and contribute

## Acceptance Criteria
AS a developer
GIVEN I want to learn how the project works
WHEN I have a look at the repository
THEN I should see a wiki page
AND it should detail the aspects of the bot

## Subtasks
- [ ] Create GitHub Wiki
- [ ] Document what the bot is
- [ ] Document how to setup the bot
- [ ] Document about the Google Drive Sync
- [ ] Document the web hook API
