### ISSUE TITLE
AS a user, I want there to be an inventory command I can use

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#14]
AS a user, I want there to be an inventory command I can use
SO THAT I can see what cards I have

## Acceptance Criteria
AS a user
GIVEN I want to see my full inventory
WHEN I type `/inventory`
THEN the bot should reply with a paginated list of all my cards I have in my inventory

AS a user
GIVEN I want to see a specific card from my inventory
WHEN I type `/inventory <card number>`
THEN the bot should deploy with details of that card and its image

## Subtasks
- [ ] Create base command
- [ ] Create paginated list
- [ ] Create specific card view
