### ISSUE TITLE
AS a developer, I want to be able to register commands to only specific environments

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#4]
AS a developer, I want to be able to register commands to only specific environments
SO THAT I can make testing commands only visible on the staging bot

## Acceptance Criteria
AS a developer
GIVEN I want a testing command
WHEN I register a command with the environment's DEV enum flag
THEN the bot will only register the command when the NODE_ENV is dev

AS a developer
GIVEN I want a testing command
WHEN I register a command with the environment's STAGE enum flag
THEN the bot will only register the command when the NODE_ENV is stage

AS a developer
GIVEN I want a testing command
WHEN I register a command with the environment's PROD enum flag
THEN the bot will only register the command when the NODE_ENV is prod

## Subtasks
- [x] Create environment enum flag
- [x] Initialise enum flag upon bot load
- [x] Register commands to only the current enum flag or if its null
- [x] Fix conflicting merge
- [ ] Fix changes requested

**Comment by Vylpes** [comment]
No longer needed
