### ISSUE TITLE
AS a user, I want to be able to sort the inventory command by card id, name, and type

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#90]
SO THAT I can sort it in an order of the type I am looking for

## Acceptance Criteria

GIVEN I am a user
WHEN I run `/inventory <sortBy=id|name|type>
THEN the cards will be sorted within the series by its id (default), name, or type, respectively

## Subtasks

- [ ] Update the command to accept this parameter
- [ ] Update generation logic to sort by a custom field
- [ ] Update the pagination

## Notes

- The default will be "id"
