### ISSUE TITLE
Consumables

### ISSUE THREAD

**Issue by Vylpes** [Vylpes/card-drop#99]
- [ ] AS a developer, I want there to be the concept of effects created in the codebase
- [ ] AS a user, I want to be able to list all the effects I have in my inventory
- [ ] AS a user, I want to be able to use an effect I have in my inventory
- [ ] AS a user, I want to be able to buy more effects
